<?php

declare(strict_types=1);

################################################################################
# Script:   System.Locals.ips.php
# Version:  1.3.20242112
# Author:   Heiko Wilknitz (@Pitti)
#
# Private Schlüssel und Definitionen für globale Scripte!
#
# ------------------------------ Changelog -------------------------------------
#
# 15.03.2023 - Initalversion (v1.0)
# 25.06.2024 - __TILE Definitionen hinzugefügt (v1.1)
# 09.09.2024 - __ICONS Mapping hinzugefügt (v1.2)
# 21.12.2004 - IPS_MIN_ID & IID_LC hinzugefügt (v1.3)
#
################################################################################

// BITTE NICHT NICHT LÖSCHEN!
define('__IPS_MIN_ID', 10000);

// Definition für neue TILE VISU
define('__TILE_VISU_BRIGHT', 0x00CDAB);
define('__TILE_VISU_DARK',   0x24625B);
define('__TILE_VISU_CARD',   0x333438);

define('__TILE_VISU_RED',    0xF35A2C);
define('__TILE_VISU_GRAY',   0x999A9C);
define('__TILE_VISU_BLUE',   0x11A0F3);
define('__TILE_VISU_GREEN',  0x58A906);
define('__TILE_VISU_YELLOW', 0xFFC107);
define('__TILE_VISU_ORANGE', 0xFF9800);
define('__TILE_VISU_BROWN',  0xA75406);
define('__TILE_VISU_VIOLET', 0x8619E6);

define('__TILE_VISU_SCRIPT', '<script type="text/javascript" src="./preview/wwx.js"></script>');
define('__TILE_VISU_META',   '<meta name="viewport" content="width=device-width, initial-scale=1">');

// Globale Private Definition (API-Keys, API-Tockens usw.)
// Benennung des Arrays und der Schlüssel kann jeder selber definieren!
define('__WWX', [
    // Webfront-ID für Notifcation
    'VID_WF'    => 1,
    // TileVisu-ID für Notifcation
    'VID_TV'    => 1,
    // CCUx Service IP
    'CCU_IP'    => '127.0.0.1',
    // Location Control ID
    'IID_LC'    => 1,
    // weitere Einträge
    'MY_APIKEY' => 'xyz-xyz-xyz',
    // ....
]);

// Icon Mapping Array von Webfront auf TileVisu
define('__ICONS', [
    'Aircraft' => 'plane-up',
    'Alert' => 'bell-on',
    'ArrowRight' => 'right-long',
    'Backspace' => 'caret-left',
    'Basement' => 'house',
    'Bath' => 'bath',
    'Battery' => 'car-battery',
    'Bed' => 'bed',
    'Bike' => 'bicycle',
    'Book' => 'book',
    'Bulb' => 'lightbulb',
    'Calendar' => 'calendar-day',
    'Camera' => 'camera',
    'Car' => 'car-side',
    'Caret' => 'i',
    'Cat' => 'cat',
    'Climate' => 'arrows-spin',
    'Clock' => 'clock',
    'Close' => 'xmark',
    'CloseAll' => 'xmark-large',
    'Cloud' => 'cloud',
    'Cloudy' => 'clouds',
    'Cocktail' => 'martini-glass',
    'Cross' => 'xmark',
    'Database' => 'database',
    'Dining' => 'utensils',
    'Distance' => 'arrows-left-right-to-line',
    'DoctorBag' => 'briefcase-medical',
    'Dog' => 'dog',
    'Doll' => 'nesting-dolls',
    'Dollar' => 'dollar-sign',
    'Door' => 'door-closed',
    'Download' => 'download',
    'Drops' => 'raindrops',
    'Duck' => 'duck',
    'Edit' => 'pen',
    'Electricity' => 'bolt',
    'EnergyProduction' => 'circle-bolt',
    'EnergySolar' => 'solar-panel',
    'EnergyStorage' => 'square-bolt',
    'ErlenmeyerFlask' => 'flask-round-potion',
    'Euro' => 'euro-sign',
    'Execute' => 'hand-back-point-up',
    'Eyes' => 'eye',
    'Factory' => 'industry',
    'Favorite' => 'star',
    'Female' => 'venus',
    'Fitness' => 'dumbbell',
    'Flag' => 'flag',
    'Flame' => 'fire-flame-curved',
    'FloorLamp' => 'lamp-floor',
    'Flower' => 'flower',
    'Fog' => 'cloud-fog',
    'Garage' => 'garage',
    'Gas' => 'gas-pump',
    'Gauge' => 'gauge',
    'Gear' => 'wrench-simple',
    'Graph' => 'chart-line',
    'GroundFloor' => 'house',
    'Handicap' => 'wheelchair',
    'Heart' => 'heart',
    'Help' => 'note-medical',
    'HollowArrowDown' => 'chevron-down',
    'HollowArrowLeft' => 'chevron-left',
    'HollowArrowRight' => 'chevron-right',
    'HollowArrowUp' => 'chevron-up',
    'HollowDoubleArrowDown' => 'chevrons-down',
    'HollowDoubleArrowLeft' => 'chevrons-left',
    'HollowDoubleArrowRight' => 'chevrons-right',
    'HollowDoubleArrowUp' => 'chevrons-up',
    'HollowLargeArrowDown' => 'angle-down',
    'HollowLargeArrowLeft' => 'angle-left',
    'HollowLargeArrowRight' => 'angle-right',
    'HollowLargeArrowUp' => 'angle-up',
    'Hourglass' => 'hourglass-half',
    'HouseRemote' => 'house-signal',
    'Image' => 'image',
    'Information' => 'info',
    'Intensity' => 'signal',
    'Internet' => 'globe',
    'IPS' => 'house',
    'Jalousie' => 'shutters',
    'Key' => 'key',
    'Keyboard' => 'keyboard',
    'Kitchen' => 'kitchen-set',
    'Leaf' => 'leaf',
    'Light' => 'lightbulb',
    'Lightning' => 'cloud-bolt',
    'Link' => 'share',
    'Lock' => 'lock-keyhole',
    'LockClosed' => 'lock',
    'LockOpen' => 'lock-open',
    'Macro' => 'puzzle',
    'Mail' => 'envelope',
    'Male' => 'mars',
    'Melody' => 'music',
    'Menu' => 'grid',
    'Minus' => 'minus',
    'Mobile' => 'mobile',
    'Moon' => 'moon',
    'Motion' => 'person-running',
    'Move' => 'arrows-up-down-left-right',
    'Music' => 'music',
    'Network' => 'network-wired',
    'Notebook' => 'laptop',
    'Ok' => 'check',
    'Pacifier' => 'baby',
    'Paintbrush' => 'paintbrush',
    'Pants' => '',
    'Party' => 'champagne-glass',
    'People' => 'users',
    'Plug' => 'plug',
    'Plus' => 'plus',
    'Popcorn' => 'popcorn',
    'Power' => 'power-off',
    'Presence' => 'house-user',
    'Radiator' => 'heat',
    'Raffstore' => 'blinds-open',
    'Rainfall' => 'cloud-showers',
    'Recycling' => 'recycle',
    'Remote' => 'mobile-signal-out',
    'Repeat' => 'rotate-right',
    'Return' => 'arrow-turn-down-left',
    'Robot' => 'robot',
    'Rocket' => 'rocket',
    'Script' => 'caret-right',
    'Shift' => 'arrow-up',
    'Shower' => 'shower',
    'Shuffle' => 'shuffle',
    'Shutter' => 'sort',
    'Sink' => 'sink',
    'Sleep' => 'snooze',
    'Sleet' => 'cloud-sleet',
    'Snow' => 'cloud-snow',
    'Snowflake' => 'snowflake',
    'Sofa' => 'couch',
    'Speaker' => 'volume',
    'Speedo' => 'gauge-simple',
    'Stars' => 'stars',
    'Sun' => 'sun',
    'Sunny' => 'cloud-sun',
    'Talk' => 'message-dots',
    'Tap' => 'faucet-drip',
    'Teddy' => 'teddy-bear',
    'Tee' => 'shirt',
    'Telephone' => 'phone',
    'Temperature' => 'temperature-full',
    'Thunder' => 'cloud-bolt',
    'Title' => 't',
    'TopFloor' => 'house',
    'Tree' => 'tree-deciduous',
    'TurnLeft' => 'rotate-left',
    'TurnRight' => 'rotate-right',
    'TV' => 'tv',
    'Umbrella' => 'umbrella',
    'Unicorn' => 'unicorn',
    'Ventilation' => 'fan',
    'Warning' => 'triangle-exclamation',
    'Wave' => 'water',
    'WC' => 'toilet',
    'Wellness' => 'tree-palm',
    'WindDirection' => 'compass',
    'Window' => 'window-frame',
    'WindSpeed' => 'windsock',
    'XBMC' => 'film',
    // Adaptive Icons
    'Battery-0' => 'battery-empty',
    'Battery-50' => 'battery-half',
    'Battery-100' => 'battery-full',
    'Door-0' => 'door-open',
    'Door-100' => 'door-closed',
    'EnergyStorage-0' => 'square-bolt',
    'EnergyStorage-25' => 'square-bolt',
    'EnergyStorage-50' => 'square-bolt',
    'EnergyStorage-75' => 'square-bolt',
    'EnergyStorage-100' => 'square-bolt',
    'Eyes-0' => 'eye-slash',
    'Eyes-100' => 'eye',
    'FloorLamp-0' => 'lamp-floor',
    'FloorLamp-100' => 'lamp-floor',
    'Garage-0' => 'garage-car',
    'Garage-25' => 'garage-open',
    'Garage-100' => 'garage',
    'Hourglass-0' => 'hourglass-half',
    'Hourglass-30' => 'hourglass-half',
    'Hourglass-60' => 'hourglass-half',
    'Hourglass-100' => 'hourglass-half',
    'Intensity-0' => 'signal-weak',
    'Intensity-25' => 'signal-fair',
    'Intensity-50' => 'signal-good',
    'Intensity-75' => 'signal-strong',
    'Intensity-100' => 'signal',
    'Jalousie-0' => 'blinds-raised',
    'Jalousie-50' => 'blinds-raised',
    'Jalousie-100' => 'blinds',
    'Light-0' => 'lightbulb',
    'Light-1' => 'lightbulb-on',
    'Light-25' => 'lightbulb-on',
    'Light-50' => 'lightbulb-on',
    'Light-75' => 'lightbulb-on',
    'Light-100' => 'lightbulb-on',
    'Lock-0' => 'lock-keyhole-open',
    'Lock-100' => 'lock-keyhole',
    'Presence-0' => 'house-blank',
    'Presence-100' => 'house-user',
    'Raffstore-0' => 'blinds-raised',
    'Raffstore-50' => 'blinds-raised',
    'Raffstore-100' => 'blinds',
    'Speaker-0' => 'volume-xmark',
    'Speaker-1' => 'volume-off',
    'Speaker-25' => 'volume-low',
    'Speaker-50' => 'volume',
    'Speaker-100' => 'volume-high',
    'Speedo-0' => 'gauge-simple-min',
    'Speedo-25' => 'gauge-simple-low',
    'Speedo-50' => 'gauge-simple',
    'Speedo-75' => 'gauge-simple-high',
    'Speedo-100' => 'gauge-simple-max',
    'Temperature-0' => 'temperature-empty',
    'Temperature-25' => 'temperature-quarter',
    'Temperature-50' => 'temperature-half',
    'Temperature-75' => 'temperature-three-quarters',
    'Temperature-100' => 'temperature-full',
    'Window-0' => 'window-frame-open',
    'Window-100' => 'window-frame',
    'WindSpeed-0' => 'windsock',
    'WindSpeed-30' => 'windsock',
    'WindSpeed-60' => 'windsock',
    'WindSpeed-100' => 'windsock',
    'Clock-12-00' => 'clock-twelve',
    'Clock-12-05' => 'clock-twelve',
    'Clock-12-10' => 'clock-twelve',
    'Clock-12-15' => 'clock-twelve',
    'Clock-12-20' => 'clock-twelve',
    'Clock-12-25' => 'clock-twelve',
    'Clock-12-30' => 'clock-twelve-thirty',
    'Clock-12-35' => 'clock-twelve-thirty',
    'Clock-12-40' => 'clock-twelve-thirty',
    'Clock-12-45' => 'clock-twelve-thirty',
    'Clock-12-50' => 'clock-twelve-thirty',
    'Clock-12-55' => 'clock-twelve-thirty',
    'Clock-13-00' => 'clock-one',
    'Clock-13-05' => 'clock-one',
    'Clock-13-10' => 'clock-one',
    'Clock-13-15' => 'clock-one',
    'Clock-13-20' => 'clock-one',
    'Clock-13-25' => 'clock-one',
    'Clock-13-30' => 'clock-one-thirty',
    'Clock-13-35' => 'clock-one-thirty',
    'Clock-13-40' => 'clock-one-thirty',
    'Clock-13-45' => 'clock-one-thirty',
    'Clock-13-50' => 'clock-one-thirty',
    'Clock-13-55' => 'clock-one-thirty',
    'Clock-14-00' => 'clock-two',
    'Clock-14-05' => 'clock-two',
    'Clock-14-10' => 'clock-two',
    'Clock-14-15' => 'clock-two',
    'Clock-14-20' => 'clock-two',
    'Clock-14-25' => 'clock-two',
    'Clock-14-30' => 'clock-two-thirty',
    'Clock-14-35' => 'clock-two-thirty',
    'Clock-14-40' => 'clock-two-thirty',
    'Clock-14-45' => 'clock-two-thirty',
    'Clock-14-50' => 'clock-two-thirty',
    'Clock-14-55' => 'clock-two-thirty',
    'Clock-15-00' => 'clock-three',
    'Clock-15-05' => 'clock-three',
    'Clock-15-10' => 'clock-three',
    'Clock-15-15' => 'clock-three',
    'Clock-15-20' => 'clock-three',
    'Clock-15-25' => 'clock-three',
    'Clock-15-30' => 'clock-three-thirty',
    'Clock-15-35' => 'clock-three-thirty',
    'Clock-15-40' => 'clock-three-thirty',
    'Clock-15-45' => 'clock-three-thirty',
    'Clock-15-50' => 'clock-three-thirty',
    'Clock-15-55' => 'clock-three-thirty',
    'Clock-16-00' => 'clock-four',
    'Clock-16-05' => 'clock-four',
    'Clock-16-10' => 'clock-four',
    'Clock-16-15' => 'clock-four',
    'Clock-16-20' => 'clock-four',
    'Clock-16-25' => 'clock-four',
    'Clock-16-30' => 'clock-four-thirty',
    'Clock-16-35' => 'clock-four-thirty',
    'Clock-16-40' => 'clock-four-thirty',
    'Clock-16-45' => 'clock-four-thirty',
    'Clock-16-50' => 'clock-four-thirty',
    'Clock-16-55' => 'clock-four-thirty',
    'Clock-17-00' => 'clock-five',
    'Clock-17-05' => 'clock-five',
    'Clock-17-10' => 'clock-five',
    'Clock-17-15' => 'clock-five',
    'Clock-17-20' => 'clock-five',
    'Clock-17-25' => 'clock-five',
    'Clock-17-30' => 'clock-five-thirty',
    'Clock-17-35' => 'clock-five-thirty',
    'Clock-17-40' => 'clock-five-thirty',
    'Clock-17-45' => 'clock-five-thirty',
    'Clock-17-50' => 'clock-five-thirty',
    'Clock-17-55' => 'clock-five-thirty',
    'Clock-18-00' => 'clock-six',
    'Clock-18-05' => 'clock-six',
    'Clock-18-10' => 'clock-six',
    'Clock-18-15' => 'clock-six',
    'Clock-18-20' => 'clock-six',
    'Clock-18-25' => 'clock-six',
    'Clock-18-30' => 'clock-six-thirty',
    'Clock-18-35' => 'clock-six-thirty',
    'Clock-18-40' => 'clock-six-thirty',
    'Clock-18-45' => 'clock-six-thirty',
    'Clock-18-50' => 'clock-six-thirty',
    'Clock-18-55' => 'clock-six-thirty',
    'Clock-19-00' => 'clock-seven',
    'Clock-19-05' => 'clock-seven',
    'Clock-19-10' => 'clock-seven',
    'Clock-19-15' => 'clock-seven',
    'Clock-19-20' => 'clock-seven',
    'Clock-19-25' => 'clock-seven',
    'Clock-19-30' => 'clock-seven-thirty',
    'Clock-19-35' => 'clock-seven-thirty',
    'Clock-19-40' => 'clock-seven-thirty',
    'Clock-19-45' => 'clock-seven-thirty',
    'Clock-19-50' => 'clock-seven-thirty',
    'Clock-19-55' => 'clock-seven-thirty',
    'Clock-20-00' => 'clock-eight',
    'Clock-20-05' => 'clock-eight',
    'Clock-20-10' => 'clock-eight',
    'Clock-20-15' => 'clock-eight',
    'Clock-20-20' => 'clock-eight',
    'Clock-20-25' => 'clock-eight',
    'Clock-20-30' => 'clock-eight-thirty',
    'Clock-20-35' => 'clock-eight-thirty',
    'Clock-20-40' => 'clock-eight-thirty',
    'Clock-20-45' => 'clock-eight-thirty',
    'Clock-20-50' => 'clock-eight-thirty',
    'Clock-20-55' => 'clock-eight-thirty',
    'Clock-21-00' => 'clock-nine',
    'Clock-21-05' => 'clock-nine',
    'Clock-21-10' => 'clock-nine',
    'Clock-21-15' => 'clock-nine',
    'Clock-21-20' => 'clock-nine',
    'Clock-21-25' => 'clock-nine',
    'Clock-21-30' => 'clock-nine-thirty',
    'Clock-21-35' => 'clock-nine-thirty',
    'Clock-21-40' => 'clock-nine-thirty',
    'Clock-21-45' => 'clock-nine-thirty',
    'Clock-21-50' => 'clock-nine-thirty',
    'Clock-21-55' => 'clock-nine-thirty',
    'Clock-22-00' => 'clock-ten',
    'Clock-22-05' => 'clock-ten',
    'Clock-22-10' => 'clock-ten',
    'Clock-22-15' => 'clock-ten',
    'Clock-22-20' => 'clock-ten',
    'Clock-22-25' => 'clock-ten',
    'Clock-22-30' => 'clock-ten-thirty',
    'Clock-22-35' => 'clock-ten-thirty',
    'Clock-22-40' => 'clock-ten-thirty',
    'Clock-22-45' => 'clock-ten-thirty',
    'Clock-22-50' => 'clock-ten-thirty',
    'Clock-22-55' => 'clock-ten-thirty',
    'Clock-23-00' => 'clock-eleven',
    'Clock-23-05' => 'clock-eleven',
    'Clock-23-10' => 'clock-eleven',
    'Clock-23-15' => 'clock-eleven',
    'Clock-23-20' => 'clock-eleven',
    'Clock-23-25' => 'clock-eleven',
    'Clock-23-30' => 'clock-eleven-thirty',
    'Clock-23-35' => 'clock-eleven-thirty',
    'Clock-23-40' => 'clock-eleven-thirty',
    'Clock-23-45' => 'clock-eleven-thirty',
    'Clock-23-50' => 'clock-eleven-thirty',
    'Clock-23-55' => 'clock-eleven-thirty',
]);